package com.shahmat.game.ui.learn

import com.shahmat.game.engine.ChessEngine
import com.shahmat.game.engine.PieceColor
import com.shahmat.game.engine.PieceType
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class LearnDemoBoardTest {

    @Test
    fun demoBoardIsLegalForBothKings() {
        val board = DemoBoardFactory.build()
        assertFalse("white side to move must not already be in check", board.isInCheck(PieceColor.WHITE))
        val blackCanMove = DemoBoardFactory.build()
        blackCanMove.whiteToMove = false
        assertFalse("black must not be in check", blackCanMove.isInCheck(PieceColor.BLACK))
    }

    @Test
    fun demoBoardHasLegalMoves() {
        val board = DemoBoardFactory.build()
        assertTrue("demo board must have legal moves", board.generateLegalMoves().isNotEmpty())
    }

    @Test
    fun everyFigureTypeHasALegalMove() {
        val board = DemoBoardFactory.build()
        val movesByFrom = board.generateLegalMoves().groupBy { it.from }
        // Each of the 6 white figure types must have at least one capturable/movable target.
        val byType = movesByFrom
            .map { (from, _) -> board.getPiece(from)!! }
            .map { it.type }
            .toSet()

        for (type in PieceType.values()) {
            assertTrue("figure type $type must be present on the demo board with legal moves",
                byType.contains(type))
        }
    }

    @Test
    fun everyMoveTargetIsStrictlyLegal() {
        // A figure's legal targets, as the learning screen uses them, must all be legal
        // destinations produced by the engine from the (white-to-move) demo position.
        val board = DemoBoardFactory.build()
        val legalTargets = board.generateLegalMoves()
            .map { it.from to it.to }
            .toSet()
        val froms = board.generateLegalMoves().map { it.from }.distinct()
        for (from in froms) {
            val targets = board.generateLegalMoves().filter { it.from == from }.map { it.to }.toSet()
            for (target in targets) {
                assertTrue("move $from -> $target must be generated by the engine",
                    legalTargets.contains(from to target))
            }
        }
    }

    @Test
    fun pieceInfoExistsForEveryType() {
        val engine = ChessEngine() // unused but ensures engine classpath sanity
        for (type in PieceType.values()) {
            val info = PieceInfoProvider.infoFor(type)
            // Each figure must map to a real string resource so the learning screen can
            // show a name, a description and movement text for every figure.
            assertTrue("$type must have a title string resource", info.titleRes != 0)
            assertTrue("$type must have a description string resource", info.descriptionRes != 0)
            assertTrue("$type must have a movement string resource", info.movementRes != 0)
        }
    }

    // ===== Etap 47: LearnActivity behaviour (pure-JVM checks, architecture untouched) =====
    // The screen renders via Android's Activity, which cannot be driven without Robolectric
    // or an emulator (neither is present). Its logic, however, reduces to pure functions we
    // can verify here, mirroring LearnActivity's onCreate / onBoardSquareTapped flow:
    //  - "screen opens"        -> a real demo board exists with every figure type set up;
    //  - "a figure is selected"-> each figure present on the demo board has legal targets
    //                             (so tapping it can select it) and maps to teaching info;
    //  - "text is shown"       -> the info for every type on the board carries non-zero
    //                             title / description / movement string resources.
    @Test
    fun etap47LearnScreenOpensSelectsFigureAndShowsText() {
        val board = DemoBoardFactory.build()
        val moves = board.generateLegalMoves()
        val presentTypes = moves.map { it.from }
            .distinct()
            .map { board.getPiece(it)!!.type }
            .toSet()

        // "screen opens": the demo board must be set up for play (kings safe, moves exist).
        assertTrue("screen must show a usable board", moves.isNotEmpty())
        assertFalse("white side to move must not be in check", board.isInCheck(PieceColor.WHITE))

        // "a figure is selected": every type on the board has at least one legal target.
        assertTrue("all 6 figure types must be present and selectable",
            presentTypes.containsAll(PieceType.values().toList()))

        // "text is shown": selecting any of those figures shows title, description, movement.
        for (type in presentTypes) {
            val info = PieceInfoProvider.infoFor(type)
            assertTrue("$type must show a name (screen title)", info.titleRes != 0)
            assertTrue("$type must show a description", info.descriptionRes != 0)
            assertTrue("$type must show movement text", info.movementRes != 0)
        }
    }
}
